### ISSUE TITLE
Add option to install exim4-daemon-heavy instead of exim4-daemon-light

### ISSUE THREAD

**Issue by alrayyes** [saltstack-formulas/exim-formula#5]
Installed the exim4-daemon-heavy package manually (needed to fully play nice with dovecot) results in the following error:

```shell
----------
          ID: exim_install_packages
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit: run-r696b8d4c01e24148876ccf8d8601c5dd.scope
                    E: Sub-process /usr/bin/dpkg returned an error code (1)
     Started: 01:41:38.099107
    Duration: 11594.154 ms
     Changes:   
              ----------
              exim4-daemon-heavy:
                  ----------
                  new:
                  old:
                      4.89-2+deb9u1
              exim4-localscanapi-2.0:
                  ----------
                  new:
                  old:
                      1
              mail-transport-agent:
                  ----------
                  new:
                  old:
                      1
----------
```

Would be handy if exim4-daemon-heavy could ben enabled in pillar instead of light.

**Comment by Talkless** [comment]
That's rather old issue... So everyone just modifies formula by hand or it's overridden in some kind different way?

**Comment by Talkless** [comment]
@alrayyes It seems map.jinga does a lot of merging, and you can actually override in pillars like this:
```
exim:
    Debian:
        pkgs:
            - exim4-daemon-heavy
```

**Comment by Talkless** [comment]
@myii I believe this issue can be closed, _it is_ possible to specify exim4-deamon-hevy in pillars.

**Comment by alrayyes** [comment]
Thanks for the feedback. Don't host my own email anymore so I can't test. I'll take your word for it :) I honestly have no idea of what caused the issue anymore, so this can be closed.

**Comment by myii** [comment]
> @myii I believe this issue can be closed, _it is_ possible to specify exim4-deamon-hevy in pillars.

Thanks for the heads-up, @Talkless -- appreciate it.  Closing with the approval of @alrayyes as well.
